import Headr from 'next/head';

export default function Head({props}: any) {
  return (
    <>
		<Headr>
			<title>TermPush</title>
			<meta content="width=device-width, initial-scale=1" name="viewport" />
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/favicon.ico" />
			<script src="https://cdn.tailwindcss.com"></script>
			<script src="https://kit.fontawesome.com/ad32dad39c.js" crossOrigin="anonymous"></script>
		</Headr>
    </>
  )
}
